# Generated by Django 2.0 on 2018-07-03 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ola', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountcoupon',
            options={'verbose_name': 'Discount Coupon', 'verbose_name_plural': 'Discount Coupons'},
        ),
        migrations.RenameField(
            model_name='driverdocument',
            old_name='docuemnt_type',
            new_name='document_type',
        ),
        migrations.AddField(
            model_name='bankdetail',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='cab',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ola.Cab'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cab',
            name='location',
            field=geoposition.fields.GeopositionField(default=None, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='document_url',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driverdocument',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='ending_point',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='starting_point',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='bookings',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='documents',
        ),
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together={('email', 'type')},
        ),
    ]
