# Generated by Django 2.0 on 2018-07-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ola', '0002_auto_20180703_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='user_id',
        ),
    ]
